import { NextApiRequest, NextApiResponse } from 'next';
import nodemailer from 'nodemailer';

interface JobSubmissionData {
  title: string;
  company: string;
  location: string;
  rate: string;
  summary: string;
  submittedBy: string;
  submittedByEmail: string;
  posterName: string;
  submissionId: string;
}

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const jobData: JobSubmissionData = req.body;

    // Validate required fields
    const requiredFields = ['title', 'company', 'location', 'rate', 'summary', 'submittedBy', 'submittedByEmail'];
    const missingFields = requiredFields.filter(field => !jobData[field]);
    
    if (missingFields.length > 0) {
      return res.status(400).json({ 
        error: 'Missing required fields', 
        missingFields 
      });
    }

    // Create email content
    const emailSubject = `New Job Submission: ${jobData.title} at ${jobData.company}`;
    const emailBody = `
Dear JJ,

A new job has been submitted through the AllGigs job board platform.

JOB DETAILS:
============
Title: ${jobData.title}
Company: ${jobData.company}
Location: ${jobData.location}
Rate/Salary: ${jobData.rate}

Job Description:
${jobData.summary}

SUBMISSION DETAILS:
==================
Submission ID: ${jobData.submissionId}
Submitted by: ${jobData.posterName}
Submitted by email: ${jobData.submittedByEmail}
Submission time: ${new Date().toISOString()}

--
This email was automatically generated by the AllGigs Job Board system.
    `.trim();

    // Configure Nodemailer with Brevo SMTP
    const transporter = nodemailer.createTransport({
      host: process.env.BREVO_SMTP_HOST,
      port: Number(process.env.BREVO_SMTP_PORT),
      secure: false, // Brevo/Sendinblue uses STARTTLS on port 587
      auth: {
        user: process.env.BREVO_SMTP_USER,
        pass: process.env.BREVO_SMTP_PASS,
      },
      tls: {
        rejectUnauthorized: false // Allow self-signed or custom certs (for dev)
      }
    });

    // Debug: Log SMTP config (do not log password in production)
    console.log('BREVO SMTP config:', {
      host: process.env.BREVO_SMTP_HOST,
      port: process.env.BREVO_SMTP_PORT,
      user: process.env.BREVO_SMTP_USER,
      pass: process.env.BREVO_SMTP_PASS ? '***' : undefined
    });

    // Send the email
    const mailResult = await transporter.sendMail({
      from: process.env.BREVO_SMTP_USER, // Use only the SMTP user as sender
      to: 'jj@allgigs.nl',
      subject: emailSubject,
      text: emailBody,
    });
    console.log('Nodemailer sendMail result:', mailResult);

    res.status(200).json({ 
      success: true, 
      message: 'Job submission received and email sent to jj@allgigs.nl',
      submissionId: jobData.submissionId
    });
  } catch (error) {
    console.error('Error processing job submission:', error);
    res.status(500).json({ 
      error: 'Internal server error', 
      message: 'Failed to process job submission' 
    });
  }
}
