import { NextApiRequest, NextApiResponse } from 'next';
import { createClient } from '@supabase/supabase-js';

interface JobSubmissionData {
  title: string;
  company: string;
  location: string;
  rate: string;
  summary: string;
  start_date: string;
  submittedBy: string;
  submittedByEmail: string;
  posterName: string;
  submissionId: string; // will be used as job_id
}

// Initialize Supabase client for server-side usage
const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
);

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const jobData: JobSubmissionData = req.body;

    // Validate required fields
    const requiredFields = ['title', 'company', 'location', 'rate', 'summary', 'start_date', 'user_id', 'submittedByEmail'];
    const missingFields = requiredFields.filter(field => !jobData[field]);
    
    if (missingFields.length > 0) {
      return res.status(400).json({ 
        error: 'Missing required fields', 
        missingFields 
      });
    }

    // Generate unique IDs
    const job_id = crypto.randomUUID(); // for job_id
    const row_id = crypto.randomUUID(); // for primary key id

    // Create email content
    const emailSubject = `New Job Submission: ${jobData.title} at ${jobData.company}`;
    const emailBody = `
Dear JJ,

A new job has been submitted through the AllGigs job board platform.

JOB DETAILS:
============
Title: ${jobData.title}
Company: ${jobData.company}
Location: ${jobData.location}
Rate/Salary: ${jobData.rate}
Start Date: ${jobData.start_date}

Job Description:
${jobData.summary}

SUBMISSION DETAILS:
==================
Job ID: ${job_id}
Submitted by user_id: ${jobData.user_id}
Submitted by email: ${jobData.submittedByEmail}
Submission time: ${new Date().toISOString()}

--
This email was automatically generated by the AllGigs Job Board system.
    `.trim();

    // Send email to JJ (admin)
    const brevoApiKey = process.env.BREVO_API_KEY;
    if (!brevoApiKey) {
      return res.status(500).json({ error: 'Brevo API key not configured' });
    }

    // Send confirmation email to the submitter
    const submitterSubject = `You submitted a job to AllGigs.nl: ${jobData.title} at ${jobData.company}`;
    const submitterBody = `
Hi,

Thank you for submitting your job to AllGigs.nl!

We have received your job posting for:

Title: ${jobData.title}
Company: ${jobData.company}
Location: ${jobData.location}
Rate/Salary: ${jobData.rate}
Start Date: ${jobData.start_date}

Job Description:
${jobData.summary}

We are currently reviewing your submission and will get back to you as soon as possible.

If you have any questions, reply to this email.

--
The AllGigs Team
    `.trim();

    // Send to JJ
    const brevoPayloadJJ = {
      sender: { name: 'AllGigs Job Board', email: 'no-reply@allgigs.nl' },
      to: [{ email: 'jj@allgigs.nl', name: 'JJ' }],
      subject: emailSubject,
      textContent: emailBody
    };
    // Send to submitter
    const brevoPayloadSubmitter = {
      sender: { name: 'AllGigs Job Board', email: 'no-reply@allgigs.nl' },
      to: [{ email: jobData.submittedByEmail }],
      subject: submitterSubject,
      textContent: submitterBody
    };

    // Send both emails in parallel
    const [brevoResJJ, brevoResSubmitter] = await Promise.all([
      fetch('https://api.brevo.com/v3/smtp/email', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'api-key': brevoApiKey
        },
        body: JSON.stringify(brevoPayloadJJ)
      }),
      fetch('https://api.brevo.com/v3/smtp/email', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'api-key': brevoApiKey
        },
        body: JSON.stringify(brevoPayloadSubmitter)
      })
    ]);

    if (!brevoResJJ.ok) {
      const errorData = await brevoResJJ.json();
      console.error('Brevo API error (JJ):', errorData);
      return res.status(500).json({ error: 'Failed to send email to JJ via Brevo', details: errorData });
    }
    if (!brevoResSubmitter.ok) {
      const errorData = await brevoResSubmitter.json();
      console.error('Brevo API error (submitter):', errorData);
      return res.status(500).json({ error: 'Failed to send confirmation email to submitter via Brevo', details: errorData });
    }

    // Only insert into Supabase if both emails succeed
    const { error: dbError } = await supabase
      .from('new_freelance_job')
      .insert([
        {
          id: row_id, // unique row id (primary key)
          user_id: jobData.user_id, // the user who submitted the job
          created_at: new Date().toISOString(),
          Title: jobData.title,
          Company: jobData.company,
          Location: jobData.location,
          Rate: jobData.rate,
          Summary: jobData.summary,
          job_id: job_id, // valid uuid for job reference
          StartDate: jobData.start_date,
          submitted_by_email: jobData.submittedByEmail
        }
      ]);
    if (dbError) {
      console.error('Supabase insert error:', dbError);
      return res.status(500).json({ error: 'Failed to save job to database', details: dbError.message, full: dbError });
    }

    res.status(200).json({ 
      success: true, 
      message: 'Job submission saved and email sent to jj@allgigs.nl',
      job_id: job_id
    });
  } catch (error) {
    console.error('Error processing job submission:', error);
    res.status(500).json({ 
      error: 'Internal server error', 
      message: 'Failed to process job submission' 
    });
  }
}
